// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secco.NotificationHub.Infrastructure.Contexts;

#nullable disable

namespace Secco.NotificationHub.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(NotificationHubDbContext))]
    [Migration("20260716231320_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Secco.NotificationHub.Domain.Samples.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_sample");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ds_name");

                    b.HasKey("Id")
                        .HasName("pk_samples");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_samples_dt_created_at");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_samples_ds_name");

                    b.ToTable("tb_samples");
                });
#pragma warning restore 612, 618
        }
    }
}
