// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secco.NotificationHub.Infrastructure.Contexts;

#nullable disable

namespace Secco.NotificationHub.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(NotificationHubDbContext))]
    partial class NotificationHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Secco.NotificationHub.Domain.Channels.ChannelConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_channel_configuration");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ds_channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_destination");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("fl_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_updated_at");

                    b.HasKey("Id")
                        .HasName("pk_channel_configurations");

                    b.HasIndex("Channel")
                        .IsUnique()
                        .HasDatabaseName("uk_channel_configurations_ds_channel");

                    b.ToTable("tb_channel_configurations");
                });

            modelBuilder.Entity("Secco.NotificationHub.Domain.InAppNotifications.InAppNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_in_app_notification");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("fl_read");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_link");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_message");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_read_at");

                    b.Property<DateTimeOffset?>("ScheduledFor")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_scheduled_for");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_in_app_notifications");

                    b.HasIndex("UserId", "IsRead", "ScheduledFor")
                        .HasDatabaseName("idx_in_app_notifications_user_id_fl_read_dt_scheduled_for");

                    b.ToTable("tb_in_app_notifications");
                });

            modelBuilder.Entity("Secco.NotificationHub.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_notification");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_body");

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasColumnName("ie_channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_failure_reason");

                    b.Property<string>("Recipient")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_recipient");

                    b.Property<DateTimeOffset?>("ScheduledFor")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_scheduled_for");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_sent_at");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ds_source");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("ie_status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_subject");

                    b.Property<string>("Type")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ds_type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_notifications_dt_created_at");

                    b.HasIndex("ScheduledFor")
                        .HasDatabaseName("idx_notifications_dt_scheduled_for");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_notifications_ie_status");

                    b.HasIndex("Source", "Type")
                        .HasDatabaseName("idx_notifications_ds_source_ds_type");

                    b.ToTable("tb_notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
