// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secco.NotificationHub.Infrastructure.Contexts;

#nullable disable

namespace Secco.NotificationHub.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(NotificationHubDbContext))]
    partial class NotificationHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Secco.NotificationHub.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_notification");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_failure_reason");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_recipient");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("ie_status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_subject");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_notifications_dt_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_notifications_ie_status");

                    b.ToTable("tb_notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
