// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secco.SecureGate.Infrastructure.Contexts;

#nullable disable

namespace Secco.SecureGate.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(SecureGateDbContext))]
    [Migration("20260713225111_ClientRolesAndTenantScopedRoleNames")]
    partial class ClientRolesAndTenantScopedRoleNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Secco.SecureGate.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_tenant");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("fl_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ds_slug");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uk_tenants_ds_slug");

                    b.ToTable("tb_tenants");
                });

            modelBuilder.Entity("Secco.SecureGate.Domain.Tenants.TenantDatabase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_tenant_database");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("ds_connection_string");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ds_product");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_tenant");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant_databases");

                    b.HasIndex("TenantId", "Product")
                        .IsUnique()
                        .HasDatabaseName("uk_tenant_databases_id_fk_tenant_ds_product");

                    b.ToTable("tb_tenant_databases");
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_role");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ds_name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ds_normalized_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_tenant");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("uk_roles_id_fk_tenant_ds_normalized_name")
                        .HasFilter("[ds_normalized_name] IS NOT NULL");

                    b.ToTable("tb_roles", (string)null);
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.Identity.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pk_role_claim");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_role");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("idx_role_claims_id_fk_role");

                    b.ToTable("tb_role_claims", (string)null);
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_user");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("nr_access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ds_email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("fl_email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("fl_lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ds_normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ds_normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("fl_phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_security_stamp");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_tenant");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("fl_two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ds_user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("idx_users_ds_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("uk_users_ds_normalized_user_name")
                        .HasFilter("[ds_normalized_user_name] IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_users_id_fk_tenant");

                    b.ToTable("tb_users", (string)null);
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.Identity.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pk_user_claim");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_user");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_claims_id_fk_user");

                    b.ToTable("tb_user_claims", (string)null);
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.Identity.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_pk_login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_pk_provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_user");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_logins_id_fk_user");

                    b.ToTable("tb_user_logins", (string)null);
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pfk_user");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pfk_role");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("idx_user_roles_id_pfk_role");

                    b.ToTable("tb_user_roles", (string)null);
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.Identity.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pfk_user");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_pk_login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_pk_name");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("tb_user_tokens", (string)null);
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.OpenIddict.OidcApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_oidc_application");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ds_application_type");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ds_client_id");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_client_secret");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ds_client_type");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ds_concurrency_token");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ds_consent_type");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_display_names");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_json_web_key_set");

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_permissions");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_post_logout_redirect_uris");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_properties");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_redirect_uris");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_requirements");

                    b.Property<string>("Roles")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ds_roles");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_settings");

                    b.HasKey("Id")
                        .HasName("pk_oidc_applications");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("uk_oidc_applications_ds_client_id")
                        .HasFilter("[ds_client_id] IS NOT NULL");

                    b.ToTable("tb_oidc_applications", (string)null);
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.OpenIddict.OidcAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_oidc_authorization");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_application");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ds_concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_creation_date");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_properties");

                    b.Property<string>("Scopes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_scopes");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ds_status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("ds_subject");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ds_type");

                    b.HasKey("Id")
                        .HasName("pk_oidc_authorizations");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                        .HasDatabaseName("idx_oidc_authorizations_id_fk_application_ds_status_ds_subject_ds_type");

                    b.ToTable("tb_oidc_authorizations", (string)null);
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.OpenIddict.OidcScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_oidc_scope");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ds_concurrency_token");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_description");

                    b.Property<string>("Descriptions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_descriptions");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_display_names");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ds_name");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_properties");

                    b.Property<string>("Resources")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_resources");

                    b.HasKey("Id")
                        .HasName("pk_oidc_scopes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uk_oidc_scopes_ds_name")
                        .HasFilter("[ds_name] IS NOT NULL");

                    b.ToTable("tb_oidc_scopes", (string)null);
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.OpenIddict.OidcToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_oidc_token");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_application");

                    b.Property<Guid?>("AuthorizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_authorization");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ds_concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_creation_date");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_expiration_date");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_payload");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_properties");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_redemption_date");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ds_reference_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ds_status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("ds_subject");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ds_type");

                    b.HasKey("Id")
                        .HasName("pk_oidc_tokens");

                    b.HasIndex("AuthorizationId")
                        .HasDatabaseName("idx_oidc_tokens_id_fk_authorization");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("uk_oidc_tokens_ds_reference_id")
                        .HasFilter("[ds_reference_id] IS NOT NULL");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                        .HasDatabaseName("idx_oidc_tokens_id_fk_application_ds_status_ds_subject_ds_type");

                    b.ToTable("tb_oidc_tokens", (string)null);
                });

            modelBuilder.Entity("Secco.SecureGate.Domain.Tenants.TenantDatabase", b =>
                {
                    b.HasOne("Secco.SecureGate.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_databases_tenant");
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.Identity.Role", b =>
                {
                    b.HasOne("Secco.SecureGate.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roles_tenant");
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.Identity.RoleClaim", b =>
                {
                    b.HasOne("Secco.SecureGate.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_role");
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.Identity.User", b =>
                {
                    b.HasOne("Secco.SecureGate.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenant");
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.Identity.UserClaim", b =>
                {
                    b.HasOne("Secco.SecureGate.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_user");
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.Identity.UserLogin", b =>
                {
                    b.HasOne("Secco.SecureGate.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_user");
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.Identity.UserRole", b =>
                {
                    b.HasOne("Secco.SecureGate.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_role");

                    b.HasOne("Secco.SecureGate.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_user");
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.Identity.UserToken", b =>
                {
                    b.HasOne("Secco.SecureGate.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_user");
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.OpenIddict.OidcAuthorization", b =>
                {
                    b.HasOne("Secco.SecureGate.Infrastructure.OpenIddict.OidcApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_oidc_authorizations_oidc_application");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.OpenIddict.OidcToken", b =>
                {
                    b.HasOne("Secco.SecureGate.Infrastructure.OpenIddict.OidcApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_oidc_tokens_oidc_application");

                    b.HasOne("Secco.SecureGate.Infrastructure.OpenIddict.OidcAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId")
                        .HasConstraintName("fk_oidc_tokens_oidc_authorization");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.OpenIddict.OidcApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Secco.SecureGate.Infrastructure.OpenIddict.OidcAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
