// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Secco.NotificationHub.Infrastructure.Contexts;

#nullable disable

namespace Secco.NotificationHub.Migrations.Postgres.Migrations
{
    [DbContext(typeof(NotificationHubDbContext))]
    [Migration("20260718131119_AddInAppNotifications")]
    partial class AddInAppNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Secco.NotificationHub.Domain.InAppNotifications.InAppNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_pk_in_app_notification");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_read");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("ds_link");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_message");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_read_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_in_app_notifications");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("idx_in_app_notifications_user_id_fl_read");

                    b.ToTable("tb_in_app_notifications");
                });

            modelBuilder.Entity("Secco.NotificationHub.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_pk_notification");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_created_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("ds_failure_reason");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_recipient");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("ie_status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_subject");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_notifications_dt_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_notifications_ie_status");

                    b.ToTable("tb_notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
