// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secco.LogStream.Infrastructure.Contexts;

#nullable disable

namespace Secco.LogStream.Infrastructure.Migrations.SqlServer
{
    [DbContext(typeof(LogStreamDbContext))]
    [Migration("20260712035652_LogProcesses")]
    partial class LogProcesses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Secco.LogStream.Domain.LogEntries.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_log_entry");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("ie_level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_message");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_stack_trace");

                    b.HasKey("Id")
                        .HasName("pk_log_entries");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_log_entries_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_log_entries_dt_created_at");

                    b.HasIndex("CreatedAt", "Level")
                        .HasDatabaseName("idx_log_entries_dt_created_at_ie_level");

                    b.ToTable("tb_log_entries");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.LogProcesses.LogProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_log_process");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_external_reference");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ds_name");

                    b.HasKey("Id")
                        .HasName("pk_log_processes");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_log_processes_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_log_processes_dt_created_at");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_log_processes_ds_name");

                    b.ToTable("tb_log_processes");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.LogProcesses.LogProcessDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_log_process_detail");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("ie_level");

                    b.Property<Guid>("LogProcessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_log_process");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_message");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_stack_trace");

                    b.HasKey("Id")
                        .HasName("pk_log_process_details");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_log_process_details_dt_created_at");

                    b.HasIndex("LogProcessId")
                        .HasDatabaseName("idx_log_process_details_id_fk_log_process");

                    b.ToTable("tb_log_process_details");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.LogProcesses.LogProcessDetail", b =>
                {
                    b.HasOne("Secco.LogStream.Domain.LogProcesses.LogProcess", null)
                        .WithMany("Details")
                        .HasForeignKey("LogProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_log_process_details_log_process");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.LogProcesses.LogProcess", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
