// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secco.LogStream.Infrastructure.Contexts;

#nullable disable

namespace Secco.LogStream.Infrastructure.Migrations.SqlServer
{
    [DbContext(typeof(LogStreamDbContext))]
    [Migration("20260712032136_LogEntries")]
    partial class LogEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Secco.LogStream.Domain.LogEntries.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_log_entry");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("ie_level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_message");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_stack_trace");

                    b.HasKey("Id")
                        .HasName("pk_log_entries");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_log_entries_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_log_entries_dt_created_at");

                    b.HasIndex("CreatedAt", "Level")
                        .HasDatabaseName("idx_log_entries_dt_created_at_ie_level");

                    b.ToTable("tb_log_entries");
                });
#pragma warning restore 612, 618
        }
    }
}
