// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Secco.LogStream.Infrastructure.Contexts;

#nullable disable

namespace Secco.LogStream.Migrations.Postgres.Migrations
{
    [DbContext(typeof(LogStreamDbContext))]
    partial class LogStreamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Secco.LogStream.Domain.ApiCalls.ApiCallLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_pk_api_call_log");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_created_at");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("nr_duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("ds_error_message");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_http_method");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_success");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text")
                        .HasColumnName("ds_request_body");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("text")
                        .HasColumnName("ds_request_headers");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("ds_response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("nr_response_status_code");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_url");

                    b.HasKey("Id")
                        .HasName("pk_api_call_logs");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_api_call_logs_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_api_call_logs_dt_created_at");

                    b.HasIndex("CreatedAt", "IsSuccess")
                        .HasDatabaseName("idx_api_call_logs_dt_created_at_fl_success");

                    b.ToTable("tb_api_call_logs");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.LogEntries.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_pk_log_entry");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_created_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("ie_level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_message");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("ds_stack_trace");

                    b.HasKey("Id")
                        .HasName("pk_log_entries");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_log_entries_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_log_entries_dt_created_at");

                    b.HasIndex("CreatedAt", "Level")
                        .HasDatabaseName("idx_log_entries_dt_created_at_ie_level");

                    b.ToTable("tb_log_entries");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.LogProcesses.LogProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_pk_log_process");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_created_at");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("text")
                        .HasColumnName("ds_external_reference");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_name");

                    b.HasKey("Id")
                        .HasName("pk_log_processes");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_log_processes_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_log_processes_dt_created_at");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_log_processes_ds_name");

                    b.ToTable("tb_log_processes");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.LogProcesses.LogProcessDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_pk_log_process_detail");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_created_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("ie_level");

                    b.Property<Guid>("LogProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_fk_log_process");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_message");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("ds_stack_trace");

                    b.HasKey("Id")
                        .HasName("pk_log_process_details");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_log_process_details_dt_created_at");

                    b.HasIndex("LogProcessId")
                        .HasDatabaseName("idx_log_process_details_id_fk_log_process");

                    b.ToTable("tb_log_process_details");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.LogProcesses.LogProcessDetail", b =>
                {
                    b.HasOne("Secco.LogStream.Domain.LogProcesses.LogProcess", null)
                        .WithMany("Details")
                        .HasForeignKey("LogProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_log_process_details_log_process");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.LogProcesses.LogProcess", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
