// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secco.LogStream.Infrastructure.Contexts;

#nullable disable

namespace Secco.LogStream.Migrations.SqlServer
{
    [DbContext(typeof(LogStreamDbContext))]
    partial class LogStreamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Secco.LogStream.Domain.ApiCalls.ApiCallLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_api_call_log");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("nr_duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_error_message");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_http_method");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit")
                        .HasColumnName("fl_success");

                    b.Property<string>("RequestBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_request_body");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_request_headers");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int")
                        .HasColumnName("nr_response_status_code");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_url");

                    b.HasKey("Id")
                        .HasName("pk_api_call_logs");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_api_call_logs_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_api_call_logs_dt_created_at");

                    b.HasIndex("CreatedAt", "IsSuccess")
                        .HasDatabaseName("idx_api_call_logs_dt_created_at_fl_success");

                    b.ToTable("tb_api_call_logs");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.Audit.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_audit_entry");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ds_actor_id");

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_actor_name");

                    b.Property<int>("ActorType")
                        .HasColumnType("int")
                        .HasColumnName("ie_actor_type");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_metadata");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_occurred_at");

                    b.Property<string>("ResourceId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ds_resource_id");

                    b.Property<string>("ResourceType")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ds_resource_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("OccurredAt")
                        .IsDescending()
                        .HasDatabaseName("idx_audit_entries_dt_occurred_at");

                    b.HasIndex("ActorId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_entries_ds_actor_id_dt_occurred_at");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("idx_audit_entries_ds_resource_type_ds_resource_id");

                    b.ToTable("tb_audit_entries");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.LogEntries.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_log_entry");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_category");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("ie_level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_message");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ds_service_name");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_stack_trace");

                    b.HasKey("Id")
                        .HasName("pk_log_entries");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_log_entries_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_log_entries_dt_created_at");

                    b.HasIndex("ServiceName")
                        .HasDatabaseName("idx_log_entries_ds_service_name");

                    b.HasIndex("CreatedAt", "Level")
                        .HasDatabaseName("idx_log_entries_dt_created_at_ie_level");

                    b.ToTable("tb_log_entries");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.LogProcesses.LogProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_log_process");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_external_reference");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ds_name");

                    b.HasKey("Id")
                        .HasName("pk_log_processes");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_log_processes_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_log_processes_dt_created_at");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_log_processes_ds_name");

                    b.ToTable("tb_log_processes");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.LogProcesses.LogProcessDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_log_process_detail");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("ie_level");

                    b.Property<Guid>("LogProcessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_log_process");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_message");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_stack_trace");

                    b.HasKey("Id")
                        .HasName("pk_log_process_details");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_log_process_details_dt_created_at");

                    b.HasIndex("LogProcessId")
                        .HasDatabaseName("idx_log_process_details_id_fk_log_process");

                    b.ToTable("tb_log_process_details");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.LogProcesses.LogProcessDetail", b =>
                {
                    b.HasOne("Secco.LogStream.Domain.LogProcesses.LogProcess", null)
                        .WithMany("Details")
                        .HasForeignKey("LogProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_log_process_details_log_process");
                });

            modelBuilder.Entity("Secco.LogStream.Domain.LogProcesses.LogProcess", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
